name: traigger jenkins on push

on:
  push:
    branches: [master]

jobs:
  trigger-jenkins:
    runs-on: self-hosted

    steps:
      - name: trigger jenkins build
        run: |
          curl -X POST "${{ secrets.JENKINS_BUILD_INTERNAL }}"

